### ISSUE TITLE
Beacon breaks when upgrading from stable to master

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#1194]
```
root@blueos:~# /home/pi/services/beacon/main.py
2022-10-20 20:46:04.414 | DEBUG    | commonwealth.settings.manager:__init__:33 - Starting beacon settings with SettingsV3, configuration path: None
2022-10-20 20:46:04.415 | DEBUG    | commonwealth.settings.manager:load:115 - Found possible candidates for settings source: [PosixPath('/root/.config/beacon/settings-1.json')]
2022-10-20 20:46:04.416 | DEBUG    | commonwealth.settings.manager:load:117 - Checking /root/.config/beacon/settings-1.json for settings
2022-10-20 20:46:04.417 | DEBUG    | commonwealth.settings.settings:load:63 - Loading settings from file: /root/.config/beacon/settings-1.json
Traceback (most recent call last):
  File "/home/pi/services/beacon/main.py", line 235, in <module>
    beacon = Beacon()
  File "/home/pi/services/beacon/main.py", line 80, in __init__
    self.manager = Manager(SERVICE_NAME, SettingsV3)
  File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/settings/manager.py", line 37, in __init__
    self.load()
  File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/settings/manager.py", line 119, in load
    self._settings = Manager.load_from_file(self.settings_type, valid_file)
  File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/settings/manager.py", line 88, in load_from_file
    settings_data.load(file_path)
  File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/settings/settings.py", line 89, in load
    new = Pykson().from_json(result, self.__class__)
  File "/usr/local/lib/python3.9/site-packages/pykson-1.0.1-py3.9.egg/pykson/__init__.py", line 1010, in from_json
    return self._from_json_dict(data, cls, accept_unknown)
  File "/usr/local/lib/python3.9/site-packages/pykson-1.0.1-py3.9.egg/pykson/__init__.py", line 984, in _from_json_dict
    return sub_type(accept_unknown=accept_unknown, extra_attributes=extra_attributes, **data_copy)
  File "/home/pi/services/beacon/settings.py", line 162, in __init__
    super().__init__(*args, **kwargs)
  File "/home/pi/services/beacon/settings.py", line 135, in __init__
    super().__init__(*args, **kwargs)
  File "/home/pi/services/beacon/settings.py", line 102, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/settings/settings.py", line 43, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pykson-1.0.1-py3.9.egg/pykson/__init__.py", line 703, in my_custom_init
    _setattr(instance_self, key, value)
  File "/usr/local/lib/python3.9/site-packages/pykson-1.0.1-py3.9.egg/pykson/__init__.py", line 767, in __set__
    super(ObjectListField, self).__set__(instance, Pykson().from_json(value, self.item_type), test)
  File "/usr/local/lib/python3.9/site-packages/pykson-1.0.1-py3.9.egg/pykson/__init__.py", line 1012, in from_json
    return self._from_json_list(data, cls, accept_unknown)
  File "/usr/local/lib/python3.9/site-packages/pykson-1.0.1-py3.9.egg/pykson/__init__.py", line 991, in _from_json_list
    list_result.append(self.from_json(data_value_item, cls, accept_unknown))
  File "/usr/local/lib/python3.9/site-packages/pykson-1.0.1-py3.9.egg/pykson/__init__.py", line 1016, in from_json
    raise Exception('Unable to parse data of type ' + str(type(data)))
Exception: Unable to parse data of type <class 'settings.Interface'>
root@blueos:~# 
```

**Comment by Williangalvani** [comment]
This was fixed by #1167
